## 1. Load Data

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("piterfm/fifa-football-world-cup")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).
Downloading from https://www.kaggle.com/api/v1/datasets/download/piterfm/fifa-football-world-cup?dataset_version_number=26...

100%|██████████| 187k/187k [00:00<00:00, 257kB/s]

Extracting files...
Path to dataset files: /home/third/.cache/kagglehub/datasets/piterfm/fifa-football-world-cup/versions/26

In [2]:
import os
import pandas as pd

# The folder path printed by kagglehub
folder_path = "/home/third/.cache/kagglehub/datasets/piterfm/fifa-football-world-cup/versions/26"

# Find all CSV files inside that folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

if csv_files:
    # Get the full path of the first CSV file found
    full_path = os.path.join(folder_path, csv_files[0])
    print(f"Loading file: {csv_files[0]}")
    
    # Load into pandas dataframe
    df = pd.read_csv(full_path)
    print(df.head())
else:
    print("No CSV files found in this directory. Here is what is inside:")
    print(os.listdir(folder_path))

Loading file: schedule_2026.csv
         Round  Day        Date           Time  Score  Referee  Notes  Year  \
0  Group stage  Thu  2026-06-11  13:00 (22:00)    NaN      NaN    NaN  2026
1  Group stage  Thu  2026-06-11  20:00 (05:00)    NaN      NaN    NaN  2026
2  Group stage  Fri  2026-06-12  15:00 (22:00)    NaN      NaN    NaN  2026
3  Group stage  Fri  2026-06-12  18:00 (04:00)    NaN      NaN    NaN  2026
4  Group stage  Sat  2026-06-13  12:00 (22:00)    NaN      NaN    NaN  2026

        home_team           away_team
0          Mexico        South Africa
1  Korea Republic             Czechia
2          Canada  Bosnia-Herzegovina
3   United States            Paraguay
4           Qatar         Switzerland

In [3]:
df.shape

(72, 10)

In [4]:
df.columns

Index(['Round', 'Day', 'Date', 'Time', 'Score', 'Referee', 'Notes', 'Year',
       'home_team', 'away_team'],
      dtype='object')

In [11]:
df.head(10)

,Round,Day,Date,Time,Score,Referee,Notes,Year,home_team,away_team
0,Group stage,Thu,2026-06-11,13:00 (22:00),NaN,NaN,NaN,2026,Mexico,South Africa
1,Group stage,Thu,2026-06-11,20:00 (05:00),NaN,NaN,NaN,2026,Korea Republic,Czechia
2,Group stage,Fri,2026-06-12,15:00 (22:00),NaN,NaN,NaN,2026,Canada,Bosnia-Herzegovina
3,Group stage,Fri,2026-06-12,18:00 (04:00),NaN,NaN,NaN,2026,United States,Paraguay
4,Group stage,Sat,2026-06-13,12:00 (22:00),NaN,NaN,NaN,2026,Qatar,Switzerland
5,Group stage,Sat,2026-06-13,18:00 (01:00),NaN,NaN,NaN,2026,Brazil,Morocco
6,Group stage,Sat,2026-06-13,21:00 (04:00),NaN,NaN,NaN,2026,Haiti,Scotland
7,Group stage,Sat,2026-06-13,21:00 (07:00),NaN,NaN,NaN,2026,Australia,Türkiye
8,Group stage,Sun,2026-06-14,12:00 (20:00),NaN,NaN,NaN,2026,Germany,Curaçao
9,Group stage,Sun,2026-06-14,15:00 (23:00),NaN,NaN,NaN,2026,Netherlands,Japan

In [6]:
df.tail()

,Round,Day,Date,Time,Score,Referee,Notes,Year,home_team,away_team
67,Group stage,Sat,2026-06-27,17:00 (00:00),NaN,NaN,NaN,2026,Croatia,Ghana
68,Group stage,Sat,2026-06-27,19:30 (02:30),NaN,NaN,NaN,2026,Colombia,Portugal
69,Group stage,Sat,2026-06-27,19:30 (02:30),NaN,NaN,NaN,2026,Congo DR,Uzbekistan
70,Group stage,Sat,2026-06-27,21:00 (05:00),NaN,NaN,NaN,2026,Jordan,Argentina
71,Group stage,Sat,2026-06-27,21:00 (05:00),NaN,NaN,NaN,2026,Algeria,Austria

In [7]:
df.describe

<bound method NDFrame.describe of           Round  Day        Date           Time  Score  Referee  Notes  Year  \
0   Group stage  Thu  2026-06-11  13:00 (22:00)    NaN      NaN    NaN  2026
1   Group stage  Thu  2026-06-11  20:00 (05:00)    NaN      NaN    NaN  2026
2   Group stage  Fri  2026-06-12  15:00 (22:00)    NaN      NaN    NaN  2026
3   Group stage  Fri  2026-06-12  18:00 (04:00)    NaN      NaN    NaN  2026
4   Group stage  Sat  2026-06-13  12:00 (22:00)    NaN      NaN    NaN  2026
..          ...  ...         ...            ...    ...      ...    ...   ...
67  Group stage  Sat  2026-06-27  17:00 (00:00)    NaN      NaN    NaN  2026
68  Group stage  Sat  2026-06-27  19:30 (02:30)    NaN      NaN    NaN  2026
69  Group stage  Sat  2026-06-27  19:30 (02:30)    NaN      NaN    NaN  2026
70  Group stage  Sat  2026-06-27  21:00 (05:00)    NaN      NaN    NaN  2026
71  Group stage  Sat  2026-06-27  21:00 (05:00)    NaN      NaN    NaN  2026

         home_team           away_team
0           Mexico        South Africa
1   Korea Republic             Czechia
2           Canada  Bosnia-Herzegovina
3    United States            Paraguay
4            Qatar         Switzerland
..             ...                 ...
67         Croatia               Ghana
68        Colombia            Portugal
69        Congo DR          Uzbekistan
70          Jordan           Argentina
71         Algeria             Austria

[72 rows x 10 columns]>

In [8]:
df['home_team']

0             Mexico
1     Korea Republic
2             Canada
3      United States
4              Qatar
           ...
67           Croatia
68          Colombia
69          Congo DR
70            Jordan
71           Algeria
Name: home_team, Length: 72, dtype: object

In [10]:
df.isnull

<bound method DataFrame.isnull of           Round  Day        Date           Time  Score  Referee  Notes  Year  \
0   Group stage  Thu  2026-06-11  13:00 (22:00)    NaN      NaN    NaN  2026
1   Group stage  Thu  2026-06-11  20:00 (05:00)    NaN      NaN    NaN  2026
2   Group stage  Fri  2026-06-12  15:00 (22:00)    NaN      NaN    NaN  2026
3   Group stage  Fri  2026-06-12  18:00 (04:00)    NaN      NaN    NaN  2026
4   Group stage  Sat  2026-06-13  12:00 (22:00)    NaN      NaN    NaN  2026
..          ...  ...         ...            ...    ...      ...    ...   ...
67  Group stage  Sat  2026-06-27  17:00 (00:00)    NaN      NaN    NaN  2026
68  Group stage  Sat  2026-06-27  19:30 (02:30)    NaN      NaN    NaN  2026
69  Group stage  Sat  2026-06-27  19:30 (02:30)    NaN      NaN    NaN  2026
70  Group stage  Sat  2026-06-27  21:00 (05:00)    NaN      NaN    NaN  2026
71  Group stage  Sat  2026-06-27  21:00 (05:00)    NaN      NaN    NaN  2026

         home_team           away_team
0           Mexico        South Africa
1   Korea Republic             Czechia
2           Canada  Bosnia-Herzegovina
3    United States            Paraguay
4            Qatar         Switzerland
..             ...                 ...
67         Croatia               Ghana
68        Colombia            Portugal
69        Congo DR          Uzbekistan
70          Jordan           Argentina
71         Algeria             Austria

[72 rows x 10 columns]>